- CHANGELOG.md
- src/muse/readers/csv.py
Solves one cause of the empty technology error, when this is due to a modelling error. Change from warning to import/export error when commodities are not consistent between global commodities and sector data.
Fixes #38 
> Fatal error if commodities are not consistent

- .vscode/launch.json
- CHANGELOG.md
- src/muse/agents/factories.py
- src/muse/demand_share.py
- src/muse/errors.py
- src/muse/readers/csv.py
- src/muse/utilities.py
- tests/test_subsector.py
Adds a new version for the demand share that do not use retro agents - indeed, if they are present in the `Agents.csv` file, it will complain. Using this new demand share is set in the TOML file for each of the sectors. 
Fixes # NA
> Remove retro

- CHANGELOG.md
- docs/inputs/agents.rst
- docs/inputs/toml.rst
- src/muse/errors.py
- src/muse/interactions.py
- tests/test_interactions.py
Updates the documentation explaining the use of `standard_demand` and the possibility of not using retrofit agents
Fixes #47
> Remove retro docs

- CHANGELOG.md
- src/muse/hooks.py
- tests/test_agents.py
- tests/test_demand_share.py
Add tests to check the functionality added when not using retrofit agents, in particular the new capacity agent creation if there are no retro and the standard demand. 
Fixes #53
> Test no retro

- README.md
The package group is called `doc` not `docs`.
> Fix typo in instructions in README

- .github/workflows/ci.yml
This PR expands the CI system to run the tests in Python 3.8-3.9 as well as in all three platforms: Linux, Windows and MacOS. 
Close #104
> Expand CI workflow

- pyproject.toml
- setup.cfg
- setup.py
- src/muse/__main__.py
- src/muse/demand_share.py
- src/muse/filters.py
Moved most of that is possible from setup.cfg into pyproject.toml.
Added an entry point via src/muse/main.py to pyproject.toml. MUSE can now be called via `muse` command after installation
bumpversion and flake8 do not yet support pyproject.toml, and remain in setup.cfg.
NEEDS INFO: `bump2version` fails doe to incorrect initial version in setup.cfg bumpversion
Fixes #103 
Fixes #108
> Convert setup.cfg to pyproject.toml and add entrypoint.

- .github/workflows/ci.yml
- pyproject.toml
This PR addresses #105 updating the `pyproject.toml` file to include the Python versions which were included in the CI workflow in #119 . Specifically, the valid versions that MUSE can now be installed in are 3.8 and 3.9.
Closes #105
> Updating pyproject.toml with valid python versions

- pyproject.toml
License metadata was missing from `pyproject.toml`. This PR adds that metadata and also bumps the status to `Beta`, as MUSE is most definitely more stable that what `Alpha` status generally suggests. 
Having the license in `pyproject.toml` will also show the correct badge in the README after a new version is released. 
Fixes #128 
N/A
N/A
> Update pyproject.toml with license information

- .github/workflows/broken-link-check.yml
- CHANGELOG.md
Updates the relevant workflow file to run the links checker of the documentation only automatically on Sundays (or manually), rather than when there are PRs or pushes to any branch.
Fixes #147
N/A
N/A
> Run link-checker only once a week

- codecov.yml
Adds a coverage configuration such that even if coverage goes slightly down in a PR, the CI does not fail.
> Add a coverage configuration to ease coverage gateway

- .github/workflows/ci.yml
- .github/workflows/publish.yml
- CHANGELOG.md
So far, the tests and publication steps were part of the same workflow, and which part to run were controlled depending on having a tag or not. This PR separates both activities in their own workflow files and enables the test workflow to be trigger from another workflow file, the `publish.yml` file, which is only triggered when there is a release. 
It also adds a couple of steps to this `publish` workflow to upload the wheels and the standalone executable to the release page automatically.
In summary, the steps to publish a new version now are:
1. Merge whatever is required to `main`.
2. Pull the main branch and update the version locally with `bump2version`.
3. Push the commits AND the tags.
4. Create a new release selecting the appropriate version number. Choose `Generate release …
> Separate pubslish workflow and add upload of executable to release

- CHANGELOG.md
- docs/inputs/technodata.rst
- src/muse/quantities.py
- tests/test_quantities.py
*Variable costs are dependent on capacity ib the gross margin definition, rather than being proportional to the capacity.*
Fixes #223 
> Variable costs definition

- .github/workflows/ci.yml
I recently enabled the pre-commit app for this repo, which checks the pre-commit hooks pass anyway (and also commits autofixes), so this workflow is no longer needed.
> CI: Remove pre-commit workflow

- .vscode/settings.json
The --no-cov argument is not only no longer necessary when invoking `pytest` from VS Code, but in this case, as we don't have `pytest-cov` installed, it means that the command will fail and VS Code will be unable to run the tests from the tests panel.
On another note, do we want to add `pytest-cov` to the dependencies? And on yet another note, do we want to install the codecov GitHub app so we can see coverage changes for PRs?
> VS Code: --no-cov argument no longer needed for pytest

- docs/inputs/technodata.rst
- docs/inputs/technodata_timeslices.rst
Improving the description for the `UtilizationFactor` parameter in the `TechnodataTimeslices` file, as suggested in #203. Also adding a note that Utilization factor should be between 0 and 1.
Fixes #203
> Improve documentation for `UtilizationFactor` parameter

- src/muse/constraints.py
- src/muse/readers/csv.py
- tests/test_minimum_service.py
I've fixed #320 by introducing a check in the `minimum_service` constraint function that all minimum service factors are >=0 and <= 1 and I've also amended the spurious tests accordingly.
The only thing is that I'm wondering whether this is a bit late to raise an error. Should the check be in some earlier parsing step (either in addition or instead)?
While I was reading through the docstring for `muse.constraints` I noticed some typos and fixed those while I was at it.
Fixes #320.
> Enforce minimum service factor limits

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/usage-support.md
- docs/installation/index.rst
- docs/installation/pipx-based.rst
- docs/installation/virtual-env-based.rst
There are a bunch of places in the documentation where it says "operative system" instead of "operating system", which just sounds weird. Fix this.
> Fix spelling: operative system => operating system

- src/muse/constraints.py
- src/muse/data/example/minimum_service/technodata/industry/Technodata.csv
- src/muse/readers/csv.py
- tests/test_minimum_service.py
- tests/test_readers.py
Let's try this again. It turns out the fix for my previous mistake was really trivial (5fb3ff5824ae034bd11955006001a5dde321d897). Sorry about all the noise!
Fixes #320.
> Enforce minimum service factor limits (take 2)

- tests/test_readers.py
As prepatory work for #332 this PR expands the tests for the reader functions in `readers/csv.py` to more strictly codify the expected output. So far I've only looked at `tests/test_readers.py::test_read_trade_technodata` and wanted to get initial feedback before working on others. Particularly interested on anything else about the structure of the dataset that could be checked.
> Expand reader tests

- docs/inputs/technodata.rst
- src/muse/constraints.py
As ti was being used as a fraction of the utilisation factor rather as a fraction of 100%.
Fixes #375 
> Correctly use the minimum service factor

- CITATION.cff
- docs/conf.py
- pyproject.toml
I noticed that there's still a reference to SGI in the copyright notice (you can see it in the footer of the documentation). I've updated the copyright owner to be "Imperial College London" and I changed the year while I was at it.
There was also a reference to SGI in `CITATION.cff` -- I think it refers to the old GitHub org, but I don't think that's needed: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files
FYI @ahawkes
> Remove other references to SGI

- src/muse/investments.py
I just realised that one of the changes I made in #381 broke an error message in the `scipy_match_demand` function. This fixes it
> Fix error message in `scipy_match_demand`

- pyproject.toml
Tried to upgrade Sharwari's environment for the new MUSE version and had some problems. Turns out `bottleneck` also needs to be pinned
> Pin bottleneck dependency

- docs/inputs/toml.rst
- src/muse/data/example/trade/technodata/Agents.csv
- src/muse/demand_share.py
The options have changed since the documentation was last updated, as well as the default value.
Also, whilst #349 changed the default value to "standard_demand" in the sense that if `demand_share` isn't specified in the settings file it will default to this value, if you wrote `demand_share = "default"` it would still default to "new_and_retro". So I've fixed that.
Close #341
> Update documentation for `demand_share` parameter

- .github/workflows/ci.yml
The problem is that for some reason the `CODECOV_TOKEN` GitHub secret is not available for workflows running in response to `release` events. That said, we only actually need the test coverage to be uploaded for `push` events anyway, so we can fix this by adding a conditional.
I tested this conditional by making a separate workflow that only runs in response to `push` events.
I've made this PR against `main` rather than `develop`, so we'll have to do another merge after this.
Unfortunately to fix the release I think we're going to have to delete it along with the git tag and recreate it :disappointed: 
Fixes #440.
> Fix: Upload test coverage for push events only

- .github/workflows/publish.yml
I am reliably informed by @AdrianDAlessandro that if you just specify `on: [release]` for a workflow, it will run multiple times when you create a new release. Indeed it seems that it has been running three times every time I make a new release (and I've been doing that a lot in a desperate bid to fix #443...).
> Only run release workflow once

- src/muse/agents/agent.py
- src/muse/data/example/trade/settings.toml
- src/muse/filters.py
- src/muse/readers/csv.py
- src/muse/sectors/subsector.py
- tests/conftest.py
- tests/test_filters.py
- tests/test_readers.py
Renames the incorrect spelling "threshhold" in three parameters. I've also added a warning if a user attempts to use "asset_threshhold" in the settings file. This isn't required for the other two parameters, see [here](https://github.com/EnergySystemsModellingLab/MUSE_OS/issues/301#issuecomment-2273806394)
Apparently none of these parameters are explained in the documentation, so there's nothing that needs changing in the documentation, but this obviously isn't a good thing!
Fixes #301
> Rename threshhold to threshold

- pyproject.toml
- src/muse/constraints.py
This modifies the demand-limiting capacity constraint to address the issue described in #457. I've added lots of comments to the code so hopefully everything is relatively clear, but happy to have a chat about it if not.
None of the example models are affected, as this only affects certain technologies like refineries that have multiple end-use commodities, but I've tested this with Alaa's Qatar model and the results look reasonable.
Fixes #457 
> Modify `demand_limiting_capacity` constraint

- .bumpversion.cfg
- CITATION.cff
- docs/conf.py
- src/muse/__init__.py
- src/muse/carbon_budget.py
- src/muse/mca.py
- tests/test_carbon_budget.py
This fixes a number of problems with the bisection method for setting the carbon price when using a carbon budget. 
One problem was with the calculation of initial price bounds. Firstly, the calculation of the current year in `bisection` was just wrong, which often led to `time_exp` being zero (so the upper and lower bounds would be the same). Secondly, it couldn't deal with an initial carbon price of zero (both bounds would then be zero). Thirdly, the bounds were way to narrow so unlikely to capture the solution. These are all fixed.
The main loop in the algorithm was also a mess, including the convergence criteria, so this has been tidied up and simplified (well, pretty much rewritten completely).
The `min_max_bisect` function was also a mess, so this has been tidied and comments added …
> Fix bugs in the carbon budget bisection algorithm

- docs/inputs/agents.rst
- docs/inputs/commodities.rst
- docs/inputs/existing_capacity.rst
- docs/inputs/technodata.rst
- src/muse/filters.py
This PR makes a number of small improvements to the input files section of the documentation, mostly to clarify which parameters are optional
Some parameters are still poorly explained, but other issues are open to tackle this
Fixes #198 
> More clarity in the documentation about optional parameters

- docs/inputs/toml.rst
- src/muse/__init__.py
- src/muse/__main__.py
- src/muse/examples.py
- tests/test_aggregoutput.py
- tests/test_subsector.py
To make everyone's life easier when running and developing MUSE. Currently the tests also produce log files. This might or might not be desirable.
Fixes #498
> :sparkles: Add log to file.

- src/muse/mca.py
Since demand no longer has to be fulfilled at the timeslice level (#550), I've changed this check to only check that demand is fulfilled across the whole year.
It's a bit concerning that this warning keeps being raised for the example models (not new here, this has been the case for a while). But that's another issue (#574)
> Fix demand fulfillment check

- docs/conf.py
- docs/index.rst
- docs/release-notes/index.rst
- docs/release-notes/v1.2.0.md
- docs/release-notes/v1.2.1.md
- docs/release-notes/v1.2.2.md
- docs/release-notes/v1.2.3.md
Adds release notes for versions 1.2.0 to 1.2.3 to the documentation. No problems using markdown, so could pretty much copy and paste these from github. It's all completely manual, but I think that's fine as these should be tailored to users rather than automatically built from PR names or commit messages
I also found a way to link to github issues/PRs without writing out the full URL
You can see what this all looks like [here](https://muse-os.readthedocs.io/en/documentation/)
Fixes #538
> Add release notes to documentation

- docs/inputs/technodata.rst
- src/muse/agents/factories.py
- src/muse/data/example/trade/technodata/Agents.csv
- src/muse/data/example/trade/technodata/gas/Technodata.csv
- src/muse/data/example/trade/technodata/power/Technodata.csv
- src/muse/data/example/trade/technodata/residential/Agents.csv
- src/muse/errors.py
- src/muse/readers/csv.py
- tests/test_readers.py
Agent shares are specified in the agents files, and then referenced in technodata files to assign a share of existing capacity to the agent. The names specified in the technodata files must match the agents file, otherwise an error will be raised. However, as @Jin-Jun-Mei found, in some cases even when the names do match an error can still be raised. 
The reason is that the process for reading in the agent share names is different for the agents file and technodata files. For the agents file (`read_csv_agent_parameters`), names are converted using a `sub` operation. For technodata files (`read_technodictionary`), names are first converted to snake case and then converted using a similar `sub` operation. If following conventional naming schemes, these end up being equivalent, but if you …
> Fix inconsistent reading of agent share names

- src/muse/data/example/trade/technodata/gas/CommIn.csv
- src/muse/readers/csv.py
- tests/test_readers.py
After all relevant files have been loaded, as per @tsmbland suggestion. I spotted what felt like a left-over R3 in the trade technodata and that cause the tests to fail. 
The approach is not the most elegant one - take thw whole xarray dataset, transform it to a pandas dataframe and perform the checks as before. Not the best performance-wise, but as this is done only once at the begining, performance is not an issue so opted for the path of minimum effort. 
Fixes #513
> Perform the utilisation factor check on the whole technodata dataset

- src/muse/quantities.py
- tests/test_objectives.py
- tests/test_quantities.py
Broken this off from #556 as it's relatively simple and self contained
The `consumption` function takes production data and then back-calculates commodity consumption based on the technology `CommIn`. But the calculation was all wrong
Let's say you've got a technology with the following reaction: 1A -> 2B + 3C
If you present production data of 4B & 6C to `consumption`, you should get 2A (this is the amount of A you'd need to produce 4B and 6C). To calculate this, you first need to calculate the degree of technology activity (i.e. how many units of flow do you need to produce 4B and 6C), and then multiply this by the `CommIn` quantity (in this case 1).
But previously it was summing together the output quantities (assuming they are both end-use commodities) and multiplying this by `CommIn`, …
> Fix the `consumption` function

- src/muse/agents/agent.py
- src/muse/constraints.py
- tests/test_constraints.py
- tests/test_trade.py
Constraints should only use technology parameters for a single year (the investment year), so being explicit about this by passing the constraints only the data they need
> Pass technology data only for investment year to constraints

- pyproject.toml
Regression tests broken from xarray v2025.1. I couldn't figure out why, so I'm pinning the version for now. Will open up another issue about this
Close #623
> Pin xarray version

- src/muse/agents/agent.py
- src/muse/constraints.py
- src/muse/demand_share.py
- src/muse/investments.py
- src/muse/mca.py
- src/muse/sectors/sector.py
- src/muse/sectors/subsector.py
- tests/test_agents.py
- tests/test_constraints.py
- tests/test_subsector.py
- tests/test_trade.py
This is just a refactoring change. There are many places in the code where "year" is passed around as an argument, often for the purposes of filtering the technologies dataset. We now do this filtering early on and just pass around the filtered object, so we can get rid of the need for a year argument in many places. Where year is required, it can be extracted from the `market` object. There are checks in place to make sure everything is consistent.
> Cleaner passing of current year/investment year

- src/muse/agents/agent.py
No need to filter technologies by forecast year, as technologies should already be for a single year
> Small refactor to compute_decision function

- src/muse/__init__.py
- src/muse/__main__.py
- src/muse/agents/agent.py
- src/muse/agents/factories.py
- src/muse/carbon_budget.py
- src/muse/commodities.py
- src/muse/decisions.py
- src/muse/decorators.py
- src/muse/demand_matching.py
- src/muse/demand_share.py
- src/muse/examples.py
- src/muse/filters.py
- src/muse/hooks.py
- src/muse/interactions.py
- src/muse/investments.py
- src/muse/objectives.py
- src/muse/outputs/mca.py
- src/muse/outputs/sector.py
- src/muse/outputs/sinks.py
- src/muse/production.py
- src/muse/quantities.py
- src/muse/readers/csv.py
- src/muse/readers/toml.py
- src/muse/registration.py
- src/muse/sectors/register.py
- src/muse/timeslices.py
Some files were still using the old style of type annotations. I've updated all files to use the modern syntax
Process: Added `from __future__ import annotations` to the top of every file (if not already present), and ran ruff with the `unsafe-fixes` option
> Switch to modern annotation style in all files

- src/muse/__main__.py
- src/muse/agents/agent.py
- src/muse/demand_share.py
- src/muse/examples.py
- src/muse/investments.py
- src/muse/quantities.py
- src/muse/sectors/sector.py
- src/muse/utilities.py
- tests/conftest.py
- tests/test_constraints.py
- tests/test_costs.py
- tests/test_demand_share.py
- tests/test_objectives.py
- tests/test_quantities.py
- tests/test_utilities.py
This makes a number of changes to the `broadcast_techs` function and its usage, as a follow up to #585 
- Renamed the function to `broadcast_over_assets`, which better describes its general usage
- Clarified the docstring, added example for using `installed_as_year=False`
- Removed calls to this function away from several functions in the `quantities` module (`emission`, `consumption`, `maximum_production`,`capacity_in_use`, `minimum_production`). It is now the responsibility of the code calling these functions to make sure the data is in the correct format. However, due to the check introduced in #647, any errors due to inconsistent formatting (i.e. trying to combine asset-level data with technology-level data) will be flagged, so I don't think this is any less robust. Overall, I think …
> Further improvements to `broadcast_techs`

- src/muse/outputs/mca.py
I've noticed that some of the outputs have side-effects because they modify the `market` object. They are currently performing a shallow copy on the market object before modifying, but it turns out a deep copy is required to prevent side effects 
I just noticed this because I tried adding the LCOE output to a model and found that suddenly data was missing from some of the other outputs in 2025.
> Deepcopy market object to prevent side-effects in outputs

- docs/inputs/technodata.rst
- src/muse/constraints.py
- tests/test_constraints.py
This is a small change to make the MaxCapacityAddition, MaxCapacityGrowth and TotalCapacityLimit parameters optional.
I've found that many users just set these to very high values so that the constraint effectively doesn't apply, but this is annoying and messy.
It's already possible to exclude this constraint by modifying `constraints` in settings.toml, but this is a bit fiddly and in general I don't think users should be modifying `constraints` (I encourage users to leave this out of their settings files so all the constraints are used by default).
I think the change here to make these parameters optional is more user friendly, as all users need to do now is delete the relevant columns if they don't want to use the constraint for that sector.
Close #667
> Make capacity growth parameters optional

- docs/inputs/technodata.rst
- src/muse/constraints.py
- tests/test_constraints.py
> Error message for inf growth constraints

- docs/inputs/toml.rst
- docs/tutorial-code/add-agent/1-single-objective/settings.toml
- docs/tutorial-code/add-agent/2-multiple-objective/settings.toml
- docs/tutorial-code/add-correlation-demand/1-correlation/settings.toml
- docs/tutorial-code/add-new-technology/1-introduction/settings.toml
- docs/tutorial-code/add-new-technology/2-scenario/settings.toml
- docs/tutorial-code/add-region/1-new-region/settings.toml
- docs/tutorial-code/add-service-demand/1-exogenous-demand/settings.toml
- docs/tutorial-code/carbon-budget/1-carbon-budget/settings.toml
- docs/tutorial-code/min-max-timeslice-constraints/1-min-constraint/settings.toml
- docs/tutorial-code/min-max-timeslice-constraints/2-max-constraint/settings.toml
- docs/tutorial-code/modify-timing-data/1-modify-timeslices/settings.toml
- docs/tutorial-code/modify-timing-data/2-modify-time-framework/settings.toml
- docs/tutorial-code/new-decision-metric/settings.toml
- src/muse/data/default_settings.toml
- src/muse/data/example/default/settings.toml
- src/muse/data/example/default_retro/settings.toml
- src/muse/data/example/default_timeslice/settings.toml
- src/muse/data/example/minimum_service/settings.toml
- src/muse/data/example/trade/settings.toml
- src/muse/mca.py
- tests/conftest.py
I assume at some point there was a global interest rate for all technologies, but now we specify interest rate at the technology level in the technodata files, so this global parameter isn't used.
I've deleted it from all settings files,  and added a warning to encourage users to remove it
> Delete interest_rate parameter from settings file

- tests/conftest.py
We sometimes find that tests randomly fail due to issues with randomly generated test data. Ideally we'd design the tests/fixtures in a way that wasn't so sensitive to this, but for now an easy solution is to set the random seed to a value that we know produces feasible test data.
(I initially tried 0 as the seed and all unit test runs failed, then switched to 123 and they all passed)
> Set random seed for tests

- docs/inputs/toml.rst
- src/muse/production.py
- src/muse/sectors/sector.py
The production method is overly convoluted. All it needs to do is to select a production method based on the `dispatch_production` parameter which can be either "share" or "maximum". I'm trimming it back to the minimum required for this job
Also changing the default method to "share"
Also making some improvements to the documentation. See [here](https://muse-os.readthedocs.io/en/dispatch_production/inputs/toml.html#standard-sectors)
> Simplify production module, change default method to share

- src/muse/agents/agent.py
- src/muse/examples.py
- src/muse/filters.py
- tests/test_filters.py
Tiny fix, but the `same_enduse` and `spend_limit` filters were failing because they tried to filter the `technologies` dataset by year, but it's already been filtered by year [here](https://github.com/EnergySystemsModellingLab/MUSE_OS/blob/3a0bb4aebcaaba28d41dd3d3b8f9806ed01d1b96/src/muse/sectors/sector.py#L204) so complains when trying to use these filters.
I've fixed that bug. 
Also added a check to the decorator to enforce that `technologies` cannot have a year dimension. This was a bit trickier than usual as not all filters take `technologies`, so I had to get creative using `inspect`. Not sure if there's a better way to do this.
Had to make a few other changes to keep the tests happy
EDIT: Switched to the approach suggested by Diego below
> Fix `same_enduse` and `spend_limit` filters

- src/muse/demand_share.py
- src/muse/sectors/subsector.py
- tests/test_demand_share.py
A simple refactor, which is prep-work for tackling #684
> Refactor `demand_share` module to take demand data directly

- tests/test_fullsim_regression.py
Accidentally messed this up in #672 so the regression test haven't been running for the tutorials (oops)
> Restore regressions test for tutorials

- docs/inputs/agents.rst
- src/muse/readers/csv.py
Since these will probably be removed at some point, better to let people know and discourage usage
> Add deprecation warning about retrofit agents

- src/muse/agents/factories.py
- src/muse/constraints.py
- src/muse/sectors/subsector.py
- tests/test_subsector.py
MUSE uses subsectors which are in charge of one or more commodities. Users can explicitly pass a list of commodities in the settings file, or MUSE can infer the commodities based on the `ExistingCapacity` file.
However, there's a problem with how this is done. MUSE first creates assets from the `ExistingCapacity`, then aggregates the end-use commodities from these assets. However, if there are technologies in `ExistingCapacity` with zero initial capacity, no assets will be created for these, and these won't be included in the end-use aggregation process.
E.g. a refineries sector may be in charge of oil and hydrogen. If there's no initial demand for hydrogen, the user will set initial capacity for hydrogen-producing technologies to zero. However, demand for hydrogen may increase in the …
> Fix bug defining subsector commodities when zero existing capacity

- CITATION.cff
- docs/release-notes/index.rst
- docs/release-notes/v1.4.1.md
*Please include a summary of the change and which issue is fixed (if any). Please also
include relevant motivation and context. List any dependencies that are required for
this change.*
> Release notes for v1.4.1

- src/muse/sectors/subsector.py
There was a mistake in `aggregate_enduses` introduced in #703. As well as checking which commodities are enduses (using `is_enduse`), we also need to check that technologies in the subsector produce these commodities (i.e. positive `fixed_outputs`)
Fixes #707
> Fix bug in aggregate_enduses

- tests/test_agents.py
- tests/test_aggregoutput.py
- tests/test_commodity.py
- tests/test_constraints.py
- tests/test_costs.py
- tests/test_decisions.py
- tests/test_demand_matching.py
- tests/test_demand_share.py
- tests/test_filters.py
- tests/test_interactions.py
- tests/test_investments.py
- tests/test_mca.py
- tests/test_outputs.py
- tests/test_quantities.py
- tests/test_regressions.py
- tests/test_subsector.py
- tests/test_timeslice_output.py
- tests/test_timeslices.py
- tests/test_trade.py
- tests/test_utilities.py
- tests/test_wizard.py
Following on from #720, I've gone through and used a similar approach to tidy most of the other tests
I just went through each test file one by one and got it to look at them in isolation. I haven't done anything to conftest - this is a much harder problem as the fixtures in here are used by multiple test modules. Something for another time, perhaps.
Definitely not expecting a line-by-line review. I've given it all a glance to make sure there are no glaring issues like test deletions, but it's not practical even for me to scrutinise every change. We can be reassured that all the tests are still passing, and the worst that can happen is that some things that were being tested before are no longer being tested. I'd say it's worth the risk for the benefits of readability and ease of …
> Tidy tests

- src/muse/readers/toml.py
- src/muse/sectors/preset_sector.py
- tests/test_csv_readers.py
Adding tests for a few more readers that weren't covered in #725 
We have `read_technologies` and `read_technodata`, which are mostly just wrappers over other reader functions, but there's enough processing going on that they deserve their own tests (particularly in the case of the trade model).
There's also some code in the presets factory which combines the presets data into a dataset. I've moved this into a new function and added a test for it, both for the default model and correlation model as these are a bit different
> More reader tests

- src/muse/objectives.py
Tiny bug that was breaking the timeslice_level feature 
Unfortunately, since timeslice_level is an optional parameter for most functions (mostly to make the tests easier to write) it's easy to forget to pass it, but when this happens you can end up with timeslice-mismatch errors
Consider making timeslice_level mandatory to prevent this
> Correctly pass timeslice level to capacity_to_service_demand

- src/muse/readers/toml.py
- src/muse/sectors/sector.py
A couple of bug fixes to get flexible inputs working (my fault):
- we were throwing away flexible comm_in data at the input layer due to an error in `read_technodata`
- after fixing this, this revealed an error in `market_variables` where we were passing prices data in the wrong format to the `consumption` function (which is what chooses between flexible inputs based on their price). The correct approach is to select data for the investment year, then select data for each asset based on the region of the asset (which is handled by `broadcast_over_assets`)
Only popping up now as nobody has ever used flexible inputs until now
> Fix some issues with flexible inputs

- src/muse/readers/csv.py
- src/muse/sectors/subsector.py
It was giving a confusing error message when there were any problems with the existing capacity file as it was then trying to read it as a trade file. Using a more explicit approach to prevent this
> Improved error handling for existing_capacity file

- src/muse/agents/factories.py
There was an observation from Martin/Sharwari of agents investing in technologies that should be excluded by the agent's search rule (in this case it was investing in technologies with a capital cost higher than the agent's spend limit).
I believe this is caused by `with_asset_technology` filter, which allows agents to consider all existing(/just decomissioned) asset technologies for further investment, even if those technologies don't meet the criteria of the other agent filters.
```
@register_filter
def with_asset_technology(
agent: Agent,
search_space: xr.DataArray,
**kwargs,
) -> xr.DataArray:
"""Search space *also* contains its asset technology for each asset."""
return search_space | (search_space.asset == search_space.replacement)
```
This is applied by default _even if the user …
> Don't apply the `with_asset_technology` filter by default
