CHANGELOG.md, docs/conf.py, setup.cfg
*Please include a summary of the change and which issue is fixed (if any). Please also
include relevant motivation and context. List any dependencies that are required for
this change.*
We change the name of the installed package from StarMUSE to MUSE.
#4 
=> Change package name from StarMUSE to MUSE

.readthedocs.yaml, setup.cfg
Adds a configuration file to correctly build the documentation in Read the Docs. 
@sgiarols , change the source branch in Read the Docs to this one to test if the aproach works before merging. 
=> Add configuration file for Read The Docs

.pre-commit-config.yaml, CHANGELOG.md, src/muse/objectives.py, src/muse/outputs/mca.py, src/muse/quantities.py, tests/test_constraints.py, tests/test_objectives.py, tests/test_quantities.py
Related to this issue: https://stackoverflow.com/questions/71673404/importerror-cannot-import-name-unicodefun-from-click
=> Update black version in pre-commit

CHANGELOG.md, src/muse/errors.py, src/muse/interactions.py, tests/test_interactions.py
Raise an error if no interactions are found, providing a meaningful error message.
Fixes #49
=> Add error about not finding interaction network.

CHANGELOG.md, docs/advanced-guide/Results/CacheCapacity.csv, docs/advanced-guide/extending-muse.ipynb, src/muse/outputs/cache.py, tests/test_outputs.py
Adds tutorial in the documentation about how to use the cache quantities feature. It also fixes a bug in the registered functions for caching. 
Fixes #33
=> Tutorial cached

CHANGELOG.md, src/muse/outputs/mca.py
Reporting addition of trading regions
Fixes #63 
=> add region notation

CHANGELOG.md, src/muse/outputs/mca.py
*There was an inconsistent DataArray mask creating an output error*
Fixes #68 
=> Error in slicing consumption output

.github/dependabot.yml, .github/workflows/ci.yml, .github/workflows/documentation.yml, .github/workflows/pre-commit_autoupdate.yml, .pre-commit-config.yaml, CHANGELOG.md, src/muse/carbon_budget.py, src/muse/constraints.py, src/muse/errors.py, src/muse/examples.py, src/muse/mca.py, src/muse/outputs/mca.py, src/muse/outputs/sector.py, src/muse/readers/csv.py, src/muse/readers/toml.py, src/muse/regressions.py, src/muse/sectors/legacy_sector.py, tests/conftest.py, tests/test_aggregoutput.py, tests/test_decisions.py, tests/test_outputs.py, tests/test_quantities.py, tests/test_regressions.py, tests/test_utilities.py
This PR updates several actions to the latest versions that, among other things, removes warnings/errors related to Node being outdated. Additionally, it enables Dependabot, which will keep those versions updated over time. 
The reason pre-commit autoupdate is failing is because the new version of black it is trying to use has additional rules related to formatting that result in a reformat of the code. As the code does not passes the new pre-commit clean, the update of pre-commit fails. The solution to this is to manually set the new version of black locally (23.1.0), run pre-commit in all files (forcing the re-formatting), add, commit and push. I have also done that in this PR, that is why there are plenty of files modified - only the formatting, not functionality.
Fixes #79 
Please add …
=> GitHub Actions revamp to latest versions

README.md
Reverts SGIModel/MUSE_OS#81
Update CHANGELOG to the change in README
=> Revert "Fix typo in instructions in README"

CHANGELOG.md, src/muse/regressions.py
*Foresight causes mismatch in time between demand and socio-economic drivers*
Fixes #88 
=> Removed time mismatch in regression

CHANGELOG.md, src/muse/outputs/mca.py
*Output functions were tailored only for retrofit agents. Trade output consistent*
Fixes #37, #45 
=> Output region update

CHANGELOG.md, src/muse/objectives.py
*Calculation of NPV fails automatic alignment of timeslices*
Fixes #134 
=> Updated npv summation

CHANGELOG.md, docs/inputs/toml.rst, src/muse/carbon_budget.py
*Subsectors were not included in the documentation. They are now described.*
Fixes #145 
=> Edited documentation on subsectors

.github/workflows/ci.yml
Uploads coverage report to Codecov. A badge to the README showing the coverage will be added once we have the first coverage report uploaded. 
Fixes #166
=> Upload coverage report to Codecov

CHANGELOG.md, src/muse/sectors/subsector.py
*This solves the problem of forecast not updated for agents, causing them not to estimate metrics or investments at the right time period*
Fixes #212 
=> Agents updating forecast years

CHANGELOG.md, src/muse/sectors/sector.py
*Sector-specific outputs can now report a technology-level detail*
Fixes #214 
=> Edited mca output to include technologies in sectors

src/muse/examples.py
Uses the log level in the appropriate settings file when using built in models. 
Fixes #209 
=> Fix bug log level not changed

pyproject.toml, src/muse/readers/__init__.py, src/muse/readers/csv.py, src/muse/readers/toml.py, src/muse/registration.py, src/muse/regressions.py, tests/test_agents.py, tests/test_outputs.py, tests/test_regressions.py, tests/test_utilities.py
This PR enables Ruff's own checks and fixes up the code so it passes them.
I think there are some nice little cleanups in here. Hopefully nothing too
controversial.
Closes #294.
=> Enable Ruff's own checks

.github/workflows/ci.yml
Adds codecov secrete, needed to upload reports to codecov.
Fixes #309
N/A
N/A
=> Add codecov secret

.github/workflows/ci.yml
=> CI: Enable caching of pip packages

.vscode/extensions.json
As Better TOML plugin has been deprecated - and by VS Code keeps complaining about it. 
The `prettier` pre-commit hook repo has also been archived recently which suggests there will be no more updates and it will remain in a `v4.0.0-alpha.8` state forever. Nothing to do now, but just pointing it in case it causes trouble in the future.
Fixes # N/A
=> Use Even Bettter TOML

.vscode/extensions.json
Merged the wrong branch before. 
=> Even better toml and other stuff

.bumpversion.cfg, CITATION.cff, docs/conf.py, src/muse/__init__.py
This is a pre-release version.
=> Bump version to v1.2.0rc1

src/muse/mca.py
Close #539 
Also tidying up some statements with the `or` keyword
=> Allow carbon method options to be empty

src/muse/mca.py
Clarifies the warning message that's raised when supply fails to meet demand
=> Improve warning message

docs/release-notes/index.rst, docs/release-notes/v1.3.0.md, docs/release-notes/v1.3.1.md
*Please include a summary of the change and which issue is fixed (if any). Please also
include relevant motivation and context. List any dependencies that are required for
this change.*
=> Add notes for upcoming release

src/muse/outputs/mca.py
Updating the outputs module to output LCOE/EAC at the year level, rather than timeslice level
=> Update outputs module

tests/test_constraints.py
This is mostly for my benefit so I can see what the constraint dimensions currently are
=> Test constraint dimensions

src/muse/mca.py, src/muse/outputs/cache.py, tests/test_outputs.py
*Please include a summary of the change and which issue is fixed (if any). Please also
include relevant motivation and context. List any dependencies that are required for
this change.*
=> Fix small bug to get cache working

tests/test_readers.py
I've been having a go with the Cursor AI IDE, and wanted to try it out on the relatively self-contained and harmless task of tidying up some of the tests. The main reasons for this are, firstly, to make it clearer what's actually being tested, and secondly, to make it easer to modify the tests later on if/when I make any changes to the main code. Potentially very useful, but it's such a boring job that I'd never want to do this on my own.
This was my prompt:
> Tidy this test module. Don't reorder any functions or move to other files. I want the code to be more concise, less repetitive, less redundant and more readable. Keep running to make sure the tests all pass
It then spent a few minutes making changes, running the tests, inspecting the error messages, and fixing mistakes until all the …
=> Tidy `test_readers`

docs/application-flow.rst, docs/overview.rst
Updated the description of foresight to be in line with what we're currently doing (i.e. no foresight beyond the investment year)
Fixes #195 
Fixes #196
=> Update documentation about foresight

docs/index.rst
=> Reorder documentation sections

docs/inputs/commodities.rst, docs/inputs/commodities_io.rst, docs/inputs/correlation_files.rst, docs/inputs/existing_capacity.rst, docs/inputs/inputs_csv.rst, docs/inputs/projections.rst, docs/inputs/toml.rst
=> Rename sections for input data
